obj-$(CONFIG_VIDEO_EXYNOS_FIMC_IS2) += setup-fimc-is.o
obj-$(CONFIG_VIDEO_EXYNOS_FIMC_IS2) += setup-fimc-is-sensor.o
obj-$(CONFIG_VIDEO_EXYNOS_FIMC_IS2) += setup-fimc-is-module.o
obj-$(CONFIG_COMPANION_USE) += setup-fimc-is-companion.o

obj-$(CONFIG_VIDEO_EXYNOS_FIMC_IS2) += fimc-is-v4_0_0/

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/include
